### ISSUE TITLE
Verify the Flatpak

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.torproject.torbrowser-launcher#1]
We should make this Flatpak verified just like the [old one](https://github.com/flathub/com.github.micahflee.torbrowser-launcher) was. For more details see https://flathub.org/about - Verified apps.

/cc @boklm

**Comment by TNTBOMBOM** [comment]
Yes this is important. Hope to be done asap.

**Comment by AsciiWolf** [comment]
@boklm Any chance that this could happen?

**Comment by AsciiWolf** [comment]
@boklm Any chance the Flatpak could be verified? You are the one that should be able to do it, I am not. The old Flatpak was verified.

**Comment by boklm** [comment]
It should be shown as verified now.

/close
