### ISSUE TITLE
Adapt Flathub page. Clarify install, reinstall, update. Security risk.

### ISSUE THREAD

**Issue by Francewhoa** [flathub/org.torproject.torbrowser-launcher#19]
## Challenge

About this Flathub page at https://flathub.org/apps/org.torproject.torbrowser-launcher ([archived](https://archive.ph/60eep))

The challenge is that it claims that Tor Browser Launcher (TBL) version 0.3.7 is able to automatically update Tor Browser Bundle (TBB). For most end-users this is misleading and high risk to be a disappointment. Because to them, the word "update" means that after the TBB update their TBB configuration remains. But, as you know, presently, as of April 12th, 2024, TBL is not yet able to both update TBB and keep the user's TBB configuration. What TBL presently really does is fully delete both the TBB and delete the user's TBB configuration, then reinstall a fresh TBB. 

What most users need is this:

1. First, use TBL to install TBB. Then, configuring their TBB. Some user spending hours installing and configuring modules/extensions, theme, toolbars, etc. TBL is presently successful at this.
1. Then, automatically be notified when a new TBB update is available. Then somehow be able to update it. Either via TBL or TBB. TBL is not presently able to do this.
1. Next, after the above update, their configuration remains. TBL is not presently able to do this.

--------------------

## Security Risk

Within the context of most end-user's definition of the word “automated update”, the security risk is that, after reading the present flathub page, many end-users risk to be misled into believing that their TBB is automatically be updated and their don't need to check that it is. But as you know, their TBB will not be automatically updates. Obviously, an outdated TBB is a significant security risk.

--------------------

## Suggested Resolution

Adapt this page at https://flathub.org/apps/org.torproject.torbrowser-launcher So that it clearly communicate to end-users that TBL is able to install or reinstall TBB. But does not yet support updating TBB while preserving their configuration. 

I suggest this new wording below. Changes are `highlighted with this code background` below. Feel free to adapt to your liking.

_______________ START_______________
A program to help you `download, install, reinstall, and run the Tor Browser Bundle`

Tor Browser Launcher is intended to make the Tor Browser Bundle (TBB) easier to `install` and use for GNU/Linux users. It downloads the same TBB from torproject.org that everyone else uses, and it doesn't alter it in any way. But it does make it much more usable, and it makes the task of `installing or reinstall it` more secure.

`Update TBB`

`torbrowser-launcher does NOT yet support updating TBB while preserving your configuration, such as bookmarks and extensions. This new feature is in development. All are welcome to join the efforts at https://github.com/flathub/org.torproject.torbrowser-launcher/issues/5. Meanwhile, before reinstalling TBB, if you need to keep you configuration, it is suggested to export your bookmarks and other configurations when possible. Use torbrowser-launcher to install the latest version of TBB. Then use TBB to import your configuration.`

You install torbrowser-launcher from your distribution's package manager and `it handles this:`

Downloading the most recent version of TBB for you, in your language and for your architecture
* `Automatically install or reinstall TBB. This delete all TBB present configuration if any. See note above about update is not yet supported but in development.`
* Verifying the TBB's GnuPG signature
* Includes AppArmor profiles to make a Tor Browser compromise not as bad (in some distros)
* Adding a Tor Browser application launcher to your desktop environment's menu
* Lets you set Tor Browser as your default browser
* Optionally playing a modem sound when you open Tor Browser (because Tor is so slow)

_______________ END_______________

--------------------

## Contribute

I tried to create a pull request to contribute to adapting this page at https://flathub.org/apps/org.torproject.torbrowser-launcher But found no way to do this. How can I do this? If this is not possible, what is your preference?

--------------------

## Related Ticket

https://github.com/flathub/org.torproject.torbrowser-launcher/issues/5

**Comment by AsciiWolf** [comment]
Most of the problems were already resolved with the most recent one being full file system sandboxing. TBB auto update now works fine since TBB 13.x (I believe) and the Flatpak is now verified and approved by Tor Project. Closing this ticket.
