### ISSUE TITLE
Issue: Package is inaccessible in countries where tor mirrors are blocked

### ISSUE THREAD

**Issue by oomfiee** [flathub/org.torproject.torbrowser-launcher#29]
when running the package it will try to connect to the mirrors this will not work in countries where they block tor mirrors.
which makes this package inaccessible and non-functional.

possible fix: use pre-packaged archive from tor or other 3rd party mirrors in case of the user being in the countries that do block tor and its mirrors.

**Comment by AsciiWolf** [comment]
You can launch "Tor Browser Launcher Settings" and try setting other mirror. If this does not work, the only possible workaround is to run a local Tor daemon outside of the Flatpak and point torbrowser-launcher to its IP/Port via "Tor Browser Launcher Settings".

**Comment by oomfiee** [comment]
> You can launch "Tor Browser Launcher Settings" and try setting other mirror. If this does not work, the only possible workaround is to run a local Tor daemon outside of the Flatpak and point torbrowser-launcher to its IP/Port via "Tor Browser Launcher Settings".

does not work bc if i use a mirror option the application cannot install bc it trys to check a update from a blocked domain

**Comment by oomfiee** [comment]
yes possibly using the tor daemon may work but if thats a fix then its possibly recommended to tell it in the description first
