### ISSUE TITLE
Signature Verification Failed: TB 13.0.9

### ISSUE THREAD

**Issue by TNTBOMBOM** [flathub/org.torproject.torbrowser-launcher#7]
![TB-flatpak](https://github.com/flathub/org.torproject.torbrowser-launcher/assets/11895339/299cfa51-aba8-48b8-b903-ea914c491579)

Note: Start doesnt help solve the issue, will just reback the same failed popup.

**Comment by AsciiWolf** [comment]
I just tested it and was not able to reproduce your issue. Are you sure you are using the (latest) Flatpak version?

**Comment by TNTBOMBOM** [comment]
> I just tested it and was not able to reproduce your issue. Are you sure you are using the (latest) Flatpak version?

```
user@host:~$ flatpak --version 
Flatpak 1.14.4
```

If you want further debugs please tell me.

**Comment by AsciiWolf** [comment]
Try removing the existing `~/.var/app/org.torproject.torbrowser-launcher` directory.

**Comment by TNTBOMBOM** [comment]
> Try removing the existing `~/.var/app/org.torproject.torbrowser-launcher` directory.

Same thing.

**Comment by TNTBOMBOM** [comment]
Issue solved by removing micah lee TorBrowser downloaded path: 

https://github.com/flatpak/flatpak/issues/5668#issuecomment-1913546330

Then reinstall TB from TPO new repo.

Stupid solution but dunno it resolved the issue.
