### ISSUE TITLE
Default to using XDG Desktop Portal

### ISSUE THREAD

**Issue by jbruechert** [flathub/org.torproject.torbrowser-launcher#78]
Is there a reason why this flatpak does not set `--env=GTK_USE_PORTAL=1`?
It seems to work quite well and provides are more useful way to store and open files in locations outside of the downloads directory.

**Comment by AsciiWolf** [comment]
I am not sure, but I think that the XDG file chooser portal worked fine and was used by-default in Tor Browser 13.x when running as a Flatpak.

@boklm Any idea?

**Comment by jbruechert** [comment]
Thanks!
